# Generated by Django 5.0.6 on 2026-08-12 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_boardmember_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='boards.element'),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('sticky', 'Sticky note'), ('shape', 'Shape'), ('text', 'Text'), ('image', 'Image'), ('stroke', 'Freehand stroke'), ('frame', 'Frame'), ('group', 'Group')], max_length=10),
        ),
        migrations.AlterField(
            model_name='element',
            name='z_index',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='SavedGroupTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
